bridge_node:
   ros__parameters:
      id: "raisin_bridge"
      network_type: 0 # 0 for TCP, 1 for WEBSOCKET
      network_interface: "" # for TCP

      peer_id: "server" # for TCP
      peer_ip: "192.168.12.1" # for WEBSOCKET
      topics_ros2_to_raisin: # format should be the vector of "$type, $name"
         # [""]
         ["geometry_msgs/msg/pose, generator/raw_pose",
         "std_msgs/msg/float64_multi_array, generator/ik_solutions"]
      topics_raisin_to_ros2: # format should be the vector of "$type, $name"
         # [""]
         # ["std_msgs/msg/string, string",
         # "std_msgs/msg/string, string4"]
         [""]
